Standalone code/Collect/Controllers/CollectionsController.cs
using Collect.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Collect.Controllers
{
    public class CollectionsController : Controller
    {
        // GET: Collections
        public ActionResult Index()
        {
            var db = new CustomEntities();
            var col = db.Clists.ToList();
            return View(col);
        }
    }
}

Standalone code/Collect/Controllers/EmployeeController.cs
using Collect.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Collect.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee
        public ActionResult Index()
        {
            var db = new CustomEntities();
            //var col = db.Creqs.ToList();
            var col = (from c in db.Creqs
                       where c.Status == "Assigned"
                       select c).ToList();
            return View(col);
        }
        [HttpGet]
        public ActionResult Complete(int id)
        {
            var db = new CustomEntities();
            var co = (from c in db.Creqs
                      where c.Id == id
                      select c).SingleOrDefault();
            if (co.Status == "Assigned")
            {
                return View(co);
            }
            else
            {
                return RedirectToAction("Index");
            }

        }
        [HttpPost]
        public ActionResult Complete(Creq co)
        {
            try
            {
                var db = new CustomEntities();
                var ext = (from c in db.Creqs
                           where c.Id == co.Id
                           select c).SingleOrDefault();
                co.Status = "Completed";
                db.Entry(ext).CurrentValues.SetValues(co);
                db.SaveChanges();
                var ext2 = (from c in db.Clists
                            where c.Id == co.Id
                            select c).SingleOrDefault();
                var coll = ext2;
                coll.Status = "Completed";
                db.Entry(ext2).CurrentValues.SetValues(coll);
                db.SaveChanges();
                TempData["msg"] = "Completed!";
                return RedirectToAction("Index");
            }
            catch(Exception)
            {
                TempData["msg"] = "Error!";
                return RedirectToAction("Index");
            }
            
        }
    }
}

Standalone code/Collect/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Collect.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Standalone code/Collect/Controllers/NGOController.cs
using Collect.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;

namespace Collect.Controllers
{
    public class NGOController : Controller
    {
        // GET: NGO
        public ActionResult Index()
        {
            var db = new CustomEntities();
            var col = db.Creqs.ToList();
            
            return View(col);
        }
        [HttpGet]
        public ActionResult Accept(int id)
        {
            var db = new CustomEntities();
            var co = (from c in db.Creqs
                      where c.Id == id
                      select c).SingleOrDefault();
            if (co.Status == "Pending")
            {
                return View(co);
            }
            else
            {
                TempData["msg"] = "Already accepted!";
                return RedirectToAction("Index");
            }

        }
        [HttpPost]
        public ActionResult Accept(Creq co)
        {
            try
            {
                var db = new CustomEntities();
            var ext = (from c in db.Creqs
                       where c.Id == co.Id
                       select c).SingleOrDefault();
            co.Status = "Assigned";
            var e = Convert.ToInt32(Request["EmpID"]);
            CE ce = new CE();
            ce.eid = e;
            ce.cid = co.Id;
            db.CEs.Add(ce);
            db.SaveChanges();
            var en = (from c in db.Emps
                      where c.Id == e
                      select c.Ename).SingleOrDefault();
            db.Entry(ext).CurrentValues.SetValues(co);
            db.SaveChanges();
            var ext2 = (from c in db.Clists
                       where c.Id == co.Id
                       select c).SingleOrDefault();
            var coll = ext2;
            coll.Status = "Assigned";
            coll.Ename = en;
            db.Entry(ext2).CurrentValues.SetValues(coll);
            db.SaveChanges();
            TempData["msg"] = "Accepted!";
            return RedirectToAction("Index");
            }
            catch(Exception)
            {
                TempData["msg"] = "Error";
                return RedirectToAction("Index");
            }
        }
       
    }
}

Standalone code/Collect/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Collect.DB;

namespace Collect.Controllers
{
    public class RestaurantController : Controller
    {
        // GET: Restaurant
        public ActionResult Index()
        {
            var db = new CustomEntities();
            var col = db.Creqs.ToList();
            return View(col);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Creq co)
        {
            try
            {
                var db = new CustomEntities();
                co.Status = "Pending";
                db.Creqs.Add(co);
                db.SaveChanges();
                var coll = new Clist();
                coll.Id = co.Id;
                coll.Rname = co.Rname;
                coll.Ptime = co.Ptime;
                coll.Status = co.Status;
                coll.Ename = "-";
                db.Clists.Add(coll);
                db.SaveChanges();
                TempData["msg"] = "Create successful!";
                return RedirectToAction("Index");
            }
            catch(Exception)
            {
                TempData["msg"] = "Error";
                return RedirectToAction("Index");
            }
            
        }

    }
    
}

Standalone code/Collect/Views/Collections/Index.cshtml
@{
    ViewBag.Title = "All collections";
}

<h2>All collections</h2>
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Restaurant Name</th>
        <th>Preserve Time</th>
        <th>Status</th>
        <th>Employee assigned</th>
    </tr>
    @foreach (var c in Model)
    {
        <tr>
            <th>@c.Id</th>
            <th>@c.Rname</th>
            <th>@c.Ptime</th>
            <th>@c.Status</th>
            <th>@c.Ename</th>
        </tr>
    }
</table>

Standalone code/Collect/Views/Employee/Complete.cshtml
@{
    ViewBag.Title = "Complete";
}

<h2>Complete</h2>
<form action="" method="post">
    <input type="text" name="Id" value="@Model.Id" placeholder="Id" class="form-control" readonly />
    <input type="text" name="RName" value="@Model.Rname" placeholder="Rname" class="form-control" readonly />
    <input type="text" name="Ptime" value="@Model.Ptime" placeholder="Ptime" class="form-control" readonly />
    <label>Select Employee ID</label>
    <select>
        <option>1</option>
        <option>2</option>
        <option>3</option>

    </select>
    <input type="submit" value="Submit" class="btn btn-danger" />

</form>

Standalone code/Collect/Views/Employee/Index.cshtml
@{
    ViewBag.Title = "Current collections";
}

<h2>Current collections</h2>
<span class="alert alert-info">@TempData["msg"]</span>
<br /><br />
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Restaurant Name</th>
        <th>Preserve Time</th>
        <th>Status</th>
        <th></th>
    </tr>
    @foreach (var c in Model)
    {
        <tr>
            <th>@c.Id</th>
            <th>@c.Rname</th>
            <th>@c.Ptime</th>
            <th>@c.Status</th>
            <th><a href="/employee/complete/@c.Id" class="btn btn-info">Complete</a></th>
        </tr>
    }
</table>

Standalone code/Collect/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Standalone code/Collect/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Standalone code/Collect/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Standalone code/Collect/Views/NGO/Accept.cshtml
@{
    ViewBag.Title = "Accept";
}

<h2>Accept</h2>
<form action="" method="post">
    <input type="text" name="Id" value="@Model.Id" placeholder="Id" class="form-control" readonly/>
    <input type="text" name="RName" value="@Model.Rname" placeholder="Rname" class="form-control" readonly/>
    <input type="text" name="Ptime" value="@Model.Ptime" placeholder="Ptime" class="form-control" readonly/>
    <label>Select Employee ID</label>
    <select name="EmpID">
        <option>1</option>
        <option>2</option>
        <option>3</option>

    </select>
    <input type="submit" value="Submit" class="btn btn-danger" />

</form>

Standalone code/Collect/Views/NGO/Index.cshtml
@{
    ViewBag.Title = "Collect List";
}

<h2>Collect List</h2>
<span class="alert alert-info">@TempData["msg"]</span>
<br /><br />
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Restaurant Name</th>
        <th>Preserve Time</th>
        <th>Status</th>
        <th></th>
    </tr>
    @foreach (var c in Model)
    {
        <tr>
            <th>@c.Id</th>
            <th>@c.Rname</th>
            <th>@c.Ptime</th>
            <th>@c.Status</th>
            <th><a href="/ngo/accept/@c.Id" class="btn btn-info">Accept</a></th>
            
        </tr>
    }
</table>

Standalone code/Collect/Views/Restaurant/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
<form action="" method="post">
    <input type="text" name="Rname" placeholder="Restaurant name" class="form-control" />
    <input type="text" name="Ptime" placeholder="Preserve time" class="form-control" />
    <input type="submit" value="Submit" class="btn btn-danger" />

</form>

Standalone code/Collect/Views/Restaurant/Index.cshtml
@{
    ViewBag.Title = "Open Collect Requests";
}

<h2>Open Collect Requests</h2>
<span class="alert alert-info">@TempData["msg"]</span>
<br /><br />
<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Restaurant Name</th>
        <th>Preserve Time</th>
        <th>Status</th>
    </tr>
    @foreach (var c in Model)
    {
        <tr>
            <th>@c.Id</th>
            <th>@c.Rname</th>
            <th>@c.Ptime</th>
            <th>@c.Status</th>
        </tr>
    }
</table>
<a href="/restaurant/create" class="btn btn-info">Create</a>

Standalone code/Collect/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Zero Hunger", "Index", "Collections", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("NGO", "Index", "NGO")</li>
                    <li>@Html.ActionLink("Restaurant", "Index", "Restaurant")</li>
                    <li>@Html.ActionLink("Employee", "Index", "Employee")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>